{{- if .Values.mockapi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "loadgen.fullname" . }}-mockapi
  labels:
    {{- include "loadgen.componentLabels" (dict "component" "mockapi" "context" $) | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "loadgen.componentSelectorLabels" (dict "component" "mockapi" "context" $) | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.mockapi.port }}
      targetPort: http
    - name: diagnostics
      port: {{ .Values.mockapi.diagnosticsPort }}
      targetPort: diagnostics
{{- end }}
