// Generated by ScalaSemantic MCP setup.
import sbt.*
import sbt.Keys.*

import java.nio.file.{Files, StandardCopyOption}

ThisBuild / semanticdbEnabled := true

lazy val scalaSemanticWriteClasspath =
  taskKey[File]("Write module-aware compile classpath metadata for ScalaSemantic MCP.")
lazy val scalaSemanticWriteModules =
  taskKey[File]("Write module-structure metadata for ScalaSemantic MCP.")

def scalaSemanticJsonString(value: String): String =
  "\"" + value.flatMap {
    case '"'  => "\\\""
    case '\\' => "\\\\"
    case '\b' => "\\b"
    case '\f' => "\\f"
    case '\n' => "\\n"
    case '\r' => "\\r"
    case '\t' => "\\t"
    case c if c < ' ' => "\\u%04x".format(c.toInt)
    case c => c.toString
  } + "\""

def scalaSemanticRel(root: File, file: File): String = {
  val rootPath = root.toPath.toAbsolutePath.normalize()
  val path = file.toPath.toAbsolutePath.normalize()
  if (path.startsWith(rootPath)) rootPath.relativize(path).toString else path.toString
}

ThisBuild / scalaSemanticWriteClasspath := {
  (ThisBuild / scalaSemanticWriteModules).value
  val root = (ThisBuild / baseDirectory).value
  val ids = name.all(ScopeFilter(inAnyProject)).value
  val dirs = baseDirectory.all(ScopeFilter(inAnyProject)).value
  val versions = scalaVersion.all(ScopeFilter(inAnyProject)).value
  val cps = (Compile / fullClasspath).all(ScopeFilter(inAnyProject)).value
  val modules = ids.zip(dirs).zip(versions).zip(cps).map {
    case (((id, dir), version), cp) =>
      val classpath = cp.map(_.data).distinct.map { entry =>
        "        " + scalaSemanticJsonString(scalaSemanticRel(root, entry))
      }.mkString(",\n")
      "    {\n" +
        "      \"id\": " + scalaSemanticJsonString(id) + ",\n" +
        "      \"baseDir\": " + scalaSemanticJsonString(scalaSemanticRel(root, dir)) + ",\n" +
        "      \"scalaVersion\": " + scalaSemanticJsonString(version) + ",\n" +
        "      \"configuration\": \"Compile\",\n" +
        "      \"classpath\": [\n" +
        classpath + "\n" +
        "      ]\n" +
        "    }"
  }.mkString(",\n")
  val content =
    "{\n" +
      "  \"schemaVersion\": 1,\n" +
      "  \"buildTool\": \"sbt\",\n" +
      "  \"modules\": [\n" +
      modules + "\n" +
      "  ]\n" +
      "}\n"
  val out = root / ".scala-semantic" / "classpath-sbt.json"
  IO.createDirectory(out.getParentFile)
  val current = if (out.isFile) IO.read(out) else ""
  if (current != content) {
    val tmp = out.getParentFile / (out.getName + ".tmp")
    IO.write(tmp, content)
    Files.move(tmp.toPath, out.toPath, StandardCopyOption.REPLACE_EXISTING, StandardCopyOption.ATOMIC_MOVE)
  }
  out
}

ThisBuild / scalaSemanticWriteModules := {
  val root = (ThisBuild / baseDirectory).value
  val ids = name.all(ScopeFilter(inAnyProject)).value
  val dirs = baseDirectory.all(ScopeFilter(inAnyProject)).value
  val outDirs = (Compile / classDirectory).all(ScopeFilter(inAnyProject)).value.map(_.getParentFile.getParentFile)
  val modules = ids.zip(dirs).zip(outDirs).map {
    case ((id, dir), outDir) =>
      "    {\n" +
        "      \"name\": " + scalaSemanticJsonString(id) + ",\n" +
        "      \"path_from_root\": " + scalaSemanticJsonString(scalaSemanticRel(root, dir)) + ",\n" +
        "      \"path_to_out_dir\": " + scalaSemanticJsonString(scalaSemanticRel(root, outDir)) + "\n" +
        "    }"
  }.mkString(",\n")
  val content =
    "{\n" +
      "  \"schemaVersion\": 1,\n" +
      "  \"buildTool\": \"sbt\",\n" +
      "  \"parent\": {\n" +
      "    \"name\": \"root\",\n" +
      "    \"path_from_root\": \".\",\n" +
      "    \"path_to_out_dir\": \"target\"\n" +
      "  },\n" +
      "  \"modules\": [\n" +
      modules + "\n" +
      "  ]\n" +
      "}\n"
  val out = root / ".scala-semantic" / "modules-sbt.json"
  IO.createDirectory(out.getParentFile)
  val current = if (out.isFile) IO.read(out) else ""
  if (current != content) {
    val tmp = out.getParentFile / (out.getName + ".tmp")
    IO.write(tmp, content)
    Files.move(tmp.toPath, out.toPath, StandardCopyOption.REPLACE_EXISTING, StandardCopyOption.ATOMIC_MOVE)
  }
  out
}

Global / onLoad := {
  val prev = (Global / onLoad).value
  prev.andThen { state =>
    val key = AttributeKey[Boolean]("scalaSemanticClasspathWritten")
    if (state.get(key).getOrElse(false)) state
    else {
      val newState = state.put(key, true)
      "scalaSemanticWriteModules" :: "scalaSemanticWriteClasspath" :: newState
    }
  }
}
