{{- if and .Values.gateway.enabled (not .Values.gateway.nginxConfig.existingConfigMap) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "versola.fullname" . }}-gateway-nginx
  labels:
    {{- include "versola.componentLabels" (dict "component" "gateway" "context" .) | nindent 4 }}
data:
  nginx.conf: |
    {{- if .Values.gateway.nginxConfig.content }}
    {{- .Values.gateway.nginxConfig.content | nindent 4 }}
    {{- else }}
    {{- include "versola.defaultNginxConf" . | nindent 4 }}
    {{- end }}
  proxy_params.conf: |
    {{- include "versola.defaultProxyParamsConf" . | nindent 4 }}
{{- end }}
